// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { FirePower, FirePowerData, FirePowerTableId } from "./tables/FirePower.sol";
import { CargoSpace, CargoSpaceData, CargoSpaceTableId } from "./tables/CargoSpace.sol";
import { Speed, SpeedTableId } from "./tables/Speed.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Salt, SaltTableId } from "./tables/Salt.sol";
import { Spices, SpicesTableId } from "./tables/Spices.sol";
import { Iron, IronTableId } from "./tables/Iron.sol";
import { Sugar, SugarTableId } from "./tables/Sugar.sol";
import { Coins, CoinsTableId } from "./tables/Coins.sol";
