// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoveSystem {
  function move(int256 newPositionX, int256 newPositionY) external;

  function getTerrain(int256 positionX, int256 positionY) external pure returns (uint256);

  function getObject(int256 positionX, int256 positionY) external pure returns (uint256);
}
