// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPortSystem {
  function initPort(
    uint256 xCoord,
    uint256 yCoord,
    string calldata name,
    uint256[5] calldata amounts,
    uint256[5] calldata speeds
  ) external;

  function initPort(uint256 xCoord, uint256 yCoord, uint256[5] calldata amounts, uint256[5] calldata speeds) external;

  function manufacture(bytes32 portId) external;

  function previewManufacture(bytes32 portId) external view returns (uint256[5] memory amounts);

  function getBalance(bytes32 portId) external view returns (uint256[5] memory amounts);
}
