// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPortSystem {
  function initPort(
    int256 xCoord,
    int256 yCoord,
    string calldata name,
    uint256[5] memory amounts,
    int256[5] memory speeds
  ) external;

  function simpleInitPort(int256 xCoord, int256 yCoord) external;

  function manufacture(bytes32 portId) external;

  function previewManufacture(bytes32 portId) external view returns (uint256[5] memory amounts);

  function getBalance(bytes32 portId) external view returns (uint256[5] memory amounts);
}
