// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITradeSugarSystem {
  function sell_sugar(uint256 amount) external;

  function buy_sugar(uint256 amount) external;
}
