// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IUpgradeSystem {
  function upgrade_fire_power(uint256 amount) external;

  function upgrade_fire_rate(uint256 amount) external;

  function upgrade_max_health(uint256 amount) external;

  function upgrade_cargo(uint256 amount) external;

  function upgrade_speed(uint256 amount) external;
}
